//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MellatApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewMellatEntities : DbContext
    {
        public NewMellatEntities()
            : base("name=NewMellatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbProject> tbProjects { get; set; }
        public DbSet<ViewProjectSearch> ViewProjectSearches { get; set; }
        public DbSet<ViewGharardad> ViewGharardads { get; set; }
    }
}
