//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellatWinService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapacityView1
    {
        public int prId { get; set; }
        public Nullable<int> prPeymankar { get; set; }
        public string GharardadStartTolid { get; set; }
        public string GharardadEndTolid { get; set; }
        public Nullable<int> prProjectType { get; set; }
        public string thHajmTolid { get; set; }
        public int thId { get; set; }
        public string prTitle { get; set; }
        public Nullable<int> ElhaghieId { get; set; }
    }
}
