//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellatWinService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapacityProjectDuration
    {
        public int ID { get; set; }
        public int ProjectId { get; set; }
        public int Duration { get; set; }
        public bool HasContract { get; set; }
        public Nullable<int> CapacityTypeId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> TotalNafarSaat { get; set; }
    }
}
