//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellatWinService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapacityView2
    {
        public Nullable<System.DateTime> mosDate { get; set; }
        public Nullable<System.DateTime> mosAmaliatiDate { get; set; }
        public int prId { get; set; }
        public Nullable<int> prPeymankar { get; set; }
        public Nullable<int> prProjectType { get; set; }
    }
}
