//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capacity
    {
        public int ID { get; set; }
        public int CompanyId { get; set; }
        public int Season { get; set; }
        public int CapacityTypeId { get; set; }
        public int CapacityValue { get; set; }
        public int Year { get; set; }
    }
}
