//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Definition
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string ConditionType { get; set; }
        public int PersonType { get; set; }
        public string Person { get; set; }
        public string QueryPerson { get; set; }
        public int Bahavior { get; set; }
        public int AutomationTemplateId { get; set; }
        public string Body { get; set; }
        public int QueryId { get; set; }
    }
}
