//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefinitionParam
    {
        public int ID { get; set; }
        public int DefinitionId { get; set; }
        public int ParameterId { get; set; }
        public string ParamName { get; set; }
    }
}
