//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class NewMellatEntities : DbContext
    {
        public NewMellatEntities()
            : base("name=NewMellatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbFile> tbFiles { get; set; }
        public DbSet<tbProject> tbProjects { get; set; }
        public DbSet<tbKhbregan> tbKhbregans { get; set; }
        public DbSet<prInformation> prInformations { get; set; }
        public DbSet<tbProjectPaper> tbProjectPapers { get; set; }
        public DbSet<tbNazar> tbNazars { get; set; }
        public DbSet<tbEstelamVahed> tbEstelamVaheds { get; set; }
        public DbSet<tbKhobreganMosavab> tbKhobreganMosavabs { get; set; }
        public DbSet<tbHeyatNezarat> tbHeyatNezarats { get; set; }
        public DbSet<tbHeyatNezaratMosavab> tbHeyatNezaratMosavabs { get; set; }
        public DbSet<tbShenaseNumber> tbShenaseNumbers { get; set; }
        public DbSet<vwNoEstelam> vwNoEstelams { get; set; }
        public DbSet<vwHeyatNezarat> vwHeyatNezarats { get; set; }
        public DbSet<tbTemp> tbTemps { get; set; }
        public DbSet<vwHeyatNezarat2> vwHeyatNezarat2 { get; set; }
        public DbSet<tbAccessPage> tbAccessPages { get; set; }
        public DbSet<tbAdminInPage> tbAdminInPages { get; set; }
        public DbSet<tbAdminPremission> tbAdminPremissions { get; set; }
        public DbSet<tbAdminProject> tbAdminProjects { get; set; }
        public DbSet<tbAdmin> tbAdmins { get; set; }
        public DbSet<tbAminPremissionAccess> tbAminPremissionAccesses { get; set; }
        public DbSet<tbPage> tbPages { get; set; }
        public DbSet<vwServerDate> vwServerDates { get; set; }
        public DbSet<vwMosavabDashboard> vwMosavabDashboards { get; set; }
        public DbSet<vwDashboardAmaliatiSarRedisNashode> vwDashboardAmaliatiSarRedisNashodes { get; set; }
        public DbSet<tbSooratHesab> tbSooratHesabs { get; set; }
        public DbSet<tbSooratPishNevi> tbSooratPishNevis { get; set; }
        public DbSet<tbReval> tbRevals { get; set; }
        public DbSet<vwMosavab2> vwMosavab2 { get; set; }
        public DbSet<vwMosavab4> vwMosavab4 { get; set; }
        public DbSet<vwMosavab5> vwMosavab5 { get; set; }
        public DbSet<vwMosavab6> vwMosavab6 { get; set; }
        public DbSet<vwMosavab7> vwMosavab7 { get; set; }
        public DbSet<tbChart> tbCharts { get; set; }
        public DbSet<tbPaperProject> tbPaperProjects { get; set; }
        public DbSet<tbIndex1> tbIndex1 { get; set; }
        public DbSet<tbElhaghie> tbElhaghies { get; set; }
        public DbSet<vwGharardadID> vwGharardadIDs { get; set; }
        public DbSet<tbGharardad> tbGharardads { get; set; }
        public DbSet<tbTarhPishnehadi> tbTarhPishnehadis { get; set; }
        public DbSet<vwMosavabDashboardAjam> vwMosavabDashboardAjams { get; set; }
        public DbSet<vwMosavabDashboardAmaliatiAnjam> vwMosavabDashboardAmaliatiAnjams { get; set; }
        public DbSet<vwMosavabDashboardAmaliatiTakhir> vwMosavabDashboardAmaliatiTakhirs { get; set; }
        public DbSet<vwMosavabDashboardTakhir> vwMosavabDashboardTakhirs { get; set; }
        public DbSet<SsoMapUser> SsoMapUsers { get; set; }
        public DbSet<Commission> Commissions { get; set; }
        public DbSet<vwMosavab3> vwMosavab3 { get; set; }
        public DbSet<Capacity> Capacities { get; set; }
        public DbSet<CapacityCompany> CapacityCompanies { get; set; }
        public DbSet<ProjectFinalize> ProjectFinalizes { get; set; }
        public DbSet<tbUserDepartment> tbUserDepartments { get; set; }
    
        public virtual ObjectResult<Nullable<int>> spCountNazarGharardadOk(Nullable<int> ghId)
        {
            var ghIdParameter = ghId.HasValue ?
                new ObjectParameter("ghId", ghId) :
                new ObjectParameter("ghId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spCountNazarGharardadOk", ghIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spCountNazarGharardadNotOk(Nullable<int> ghId)
        {
            var ghIdParameter = ghId.HasValue ?
                new ObjectParameter("ghId", ghId) :
                new ObjectParameter("ghId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spCountNazarGharardadNotOk", ghIdParameter);
        }
    }
}
