//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewMellatEntities1 : DbContext
    {
        public NewMellatEntities1()
            : base("name=NewMellatEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Definition> Definitions { get; set; }
        public DbSet<DefinitionParam> DefinitionParams { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<Query> Queries { get; set; }
        public DbSet<QueryParameter> QueryParameters { get; set; }
    }
}
