//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class prInformation
    {
        public int infId { get; set; }
        public Nullable<int> infType { get; set; }
        public Nullable<int> infAct { get; set; }
        public string infTitle { get; set; }
        public string Code { get; set; }
    }
}
