//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAdminProject
    {
        public int prId { get; set; }
        public Nullable<int> prProject { get; set; }
        public string prCode { get; set; }
        public Nullable<int> prType { get; set; }
    }
}
