//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbChart
    {
        public int chId { get; set; }
        public string chTitle { get; set; }
        public Nullable<long> chValue { get; set; }
        public Nullable<int> chAct { get; set; }
        public Nullable<int> chType { get; set; }
        public Nullable<int> chYear { get; set; }
        public string chBody { get; set; }
    }
}
