//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbElhaghie
    {
        public int elId { get; set; }
        public Nullable<int> elProject { get; set; }
        public string elGharardad { get; set; }
        public string elBody { get; set; }
        public Nullable<System.DateTime> elDate1 { get; set; }
        public Nullable<System.DateTime> elDate2 { get; set; }
        public Nullable<long> elPrice { get; set; }
        public string elType { get; set; }
        public Nullable<long> elPrice2 { get; set; }
        public string elBody2 { get; set; }
        public Nullable<System.DateTime> elDate3 { get; set; }
        public Nullable<System.DateTime> elDate4 { get; set; }
    }
}
