//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEstelamVahed
    {
        public int esId { get; set; }
        public Nullable<int> esProject { get; set; }
        public Nullable<int> esAct { get; set; }
        public string esVahed { get; set; }
    
        public virtual tbProject tbProject { get; set; }
    }
}
