//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFile
    {
        public int fiId { get; set; }
        public Nullable<int> fiAct { get; set; }
        public byte[] fiData { get; set; }
        public Nullable<System.DateTime> fiDate { get; set; }
        public Nullable<int> fiParent { get; set; }
        public Nullable<int> fiType { get; set; }
        public string fiTitle { get; set; }
        public string fiExt { get; set; }
    }
}
