//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGharardad
    {
        public int ghId { get; set; }
        public Nullable<int> ghAct { get; set; }
        public Nullable<int> ghProject { get; set; }
        public string ghBody { get; set; }
        public string ghCode { get; set; }
        public string ghPriceTolid { get; set; }
        public string ghPricePosh { get; set; }
        public string ghType { get; set; }
        public Nullable<bool> IsElhaghie { get; set; }
        public Nullable<int> ProposalId { get; set; }
    }
}
