//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHeyatNezarat
    {
        public tbHeyatNezarat()
        {
            this.tbShenaseNumbers = new HashSet<tbShenaseNumber>();
        }
    
        public int heId { get; set; }
        public Nullable<int> heAct { get; set; }
        public Nullable<int> heProject { get; set; }
        public string heJalaseNumber { get; set; }
        public string heJalaseDate { get; set; }
        public Nullable<bool> heIsElhaghie { get; set; }
        public Nullable<int> ProposalId { get; set; }
    
        public virtual ICollection<tbShenaseNumber> tbShenaseNumbers { get; set; }
    }
}
