//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbIndex1
    {
        public string inVahedName { get; set; }
        public string inName { get; set; }
        public string inTell { get; set; }
        public string inTitle { get; set; }
        public string inMahdodeh { get; set; }
        public string inHadaf { get; set; }
        public string inTeam { get; set; }
        public string inVaheds { get; set; }
        public string inZinaf { get; set; }
        public string inBAzeh { get; set; }
        public string inFeatures { get; set; }
        public string inTahlil { get; set; }
        public byte[] inFile { get; set; }
        public Nullable<int> inAct { get; set; }
        public Nullable<System.DateTime> inRegisterDate { get; set; }
        public Nullable<int> inProject { get; set; }
        public int inId { get; set; }
        public string inFileName { get; set; }
    }
}
