//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbKhobreganMosavab
    {
        public int mosId { get; set; }
        public Nullable<int> mosAct { get; set; }
        public Nullable<int> mosKhob { get; set; }
        public string mosShenase { get; set; }
        public string mosNumber { get; set; }
        public Nullable<System.DateTime> mosDate { get; set; }
        public Nullable<System.DateTime> mosErsalDate { get; set; }
        public Nullable<System.DateTime> mosAmaliatiDate { get; set; }
        public string mosbody { get; set; }
        public Nullable<int> mosType { get; set; }
        public string mosPropozal { get; set; }
        public Nullable<int> mosOlaviat { get; set; }
        public Nullable<int> mosProjectId { get; set; }
        public Nullable<System.DateTime> mosSRS { get; set; }
        public Nullable<System.DateTime> mosSRSanswer { get; set; }
    
        public virtual tbKhbregan tbKhbregan { get; set; }
    }
}
