//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProjectPaper
    {
        public int paId { get; set; }
        public string paShenase { get; set; }
        public string paNumber { get; set; }
        public Nullable<System.DateTime> paDate { get; set; }
        public Nullable<int> paProject { get; set; }
        public Nullable<int> paAct { get; set; }
        public Nullable<int> paType { get; set; }
        public string paBody { get; set; }
        public Nullable<int> paEdare { get; set; }
        public Nullable<int> paMainProjectId { get; set; }
        public Nullable<int> paStatus { get; set; }
    }
}
