//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSooratPishNevi
    {
        public int pishId { get; set; }
        public Nullable<int> pishProject { get; set; }
        public Nullable<int> pishAct { get; set; }
        public string pishPrice { get; set; }
        public string pishPricePlus { get; set; }
        public string pishSooratHesab { get; set; }
        public string pishHours { get; set; }
        public string pishDore { get; set; }
        public Nullable<int> pishType { get; set; }
        public Nullable<bool> pishIsNazer { get; set; }
        public Nullable<long> pishFinalPrice { get; set; }
        public Nullable<long> pishPriceArzeshAfzoode { get; set; }
        public string pishBody { get; set; }
        public Nullable<bool> pishIsSabt { get; set; }
    }
}
