//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTarhPishnehadi
    {
        public int thId { get; set; }
        public Nullable<int> thProject { get; set; }
        public Nullable<int> thYear { get; set; }
        public string thHajmTolid { get; set; }
        public string thHajmPosh { get; set; }
        public Nullable<long> thPriceTolid { get; set; }
        public Nullable<long> thPricePosh { get; set; }
        public string thModatTolid { get; set; }
        public string thModatPosh { get; set; }
        public Nullable<int> thAct { get; set; }
        public Nullable<int> thMekanizmPosh { get; set; }
        public Nullable<int> thMekanizmtolid { get; set; }
        public Nullable<int> thIsEstelamPaper { get; set; }
        public Nullable<int> thIsCancle { get; set; }
        public Nullable<int> thIsEstelamRepeat { get; set; }
        public string thBody { get; set; }
        public Nullable<bool> thIsElhaghie { get; set; }
        public string thRiskType { get; set; }
        public string thRiskTitle { get; set; }
        public string thRiskDegree { get; set; }
        public string thRiskEhtemal { get; set; }
        public string thRiskPayamad { get; set; }
        public string thRiskAnswer { get; set; }
        public string gPriceTolid { get; set; }
        public string gPricePosh { get; set; }
        public string gType { get; set; }
        public Nullable<int> ElhaghieId { get; set; }
        public Nullable<bool> NezaratMosavab { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<decimal> PriceSecurity { get; set; }
    }
}
