//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGharardadID
    {
        public int ghId { get; set; }
        public Nullable<int> ghProject { get; set; }
        public string ghCode { get; set; }
        public Nullable<bool> isElhaghie { get; set; }
        public Nullable<int> prId { get; set; }
        public string prTitle { get; set; }
        public Nullable<int> prVahed { get; set; }
        public Nullable<int> prPeymankar { get; set; }
        public Nullable<int> prProjectType { get; set; }
    }
}
