//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwHeyatNezarat
    {
        public string prTitle { get; set; }
        public int prId { get; set; }
        public Nullable<int> prVahed { get; set; }
        public Nullable<int> prProjectType { get; set; }
        public Nullable<int> prSanadType { get; set; }
        public Nullable<int> prOlaviat { get; set; }
        public Nullable<int> prPeymankar { get; set; }
        public string thHajmTolid { get; set; }
        public Nullable<long> thPriceTolid { get; set; }
        public Nullable<long> thPricePosh { get; set; }
        public string thHajmPosh { get; set; }
        public string thModatTolid { get; set; }
        public string thModatPosh { get; set; }
        public Nullable<int> thMekanizmPosh { get; set; }
        public Nullable<int> thMekanizmtolid { get; set; }
        public Nullable<int> irIsAnalyz { get; set; }
        public Nullable<int> prIsEstelamMohtavayi { get; set; }
        public Nullable<int> prTemp { get; set; }
    }
}
