//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMosavab6
    {
        public Nullable<System.DateTime> mosSRS { get; set; }
        public Nullable<System.DateTime> mosSRSanswer { get; set; }
        public Nullable<int> prPeymankar { get; set; }
        public Nullable<System.DateTime> mosDate { get; set; }
        public Nullable<int> mosOlaviat { get; set; }
        public int mosId { get; set; }
    }
}
