#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellat
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NewMellat")]
	public partial class ZarfiatDataContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ZarfiatDataContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NewMellatConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ZarfiatDataContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ZarfiatDataContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ZarfiatDataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ZarfiatDataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spZarfiat")]
		public ISingleResult<spZarfiatResult> spZarfiat([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> hajm, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> zarib, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dayAdd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> year, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(2)")] string month1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(2)")] string month2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(2)")] string month3, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> olaviat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sanadType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hajm, zarib, dayAdd, year, month1, month2, month3, olaviat, sanadType);
			return ((ISingleResult<spZarfiatResult>)(result.ReturnValue));
		}
	}
	
	public partial class spZarfiatResult
	{
		
		private System.Nullable<int> _counts;
		
		private System.Nullable<double> _sums;
		
		private string _years;
		
		private string _months;
		
		private System.Nullable<int> _prProjectType;
		
		public spZarfiatResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_counts", DbType="Int")]
		public System.Nullable<int> counts
		{
			get
			{
				return this._counts;
			}
			set
			{
				if ((this._counts != value))
				{
					this._counts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sums", DbType="Float")]
		public System.Nullable<double> sums
		{
			get
			{
				return this._sums;
			}
			set
			{
				if ((this._sums != value))
				{
					this._sums = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_years", DbType="NVarChar(5)")]
		public string years
		{
			get
			{
				return this._years;
			}
			set
			{
				if ((this._years != value))
				{
					this._years = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_months", DbType="NVarChar(2)")]
		public string months
		{
			get
			{
				return this._months;
			}
			set
			{
				if ((this._months != value))
				{
					this._months = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prProjectType", DbType="Int")]
		public System.Nullable<int> prProjectType
		{
			get
			{
				return this._prProjectType;
			}
			set
			{
				if ((this._prProjectType != value))
				{
					this._prProjectType = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
