//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellatWinService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CapacityView1> CapacityView1 { get; set; }
        public virtual DbSet<CapacityProject> CapacityProjects { get; set; }
        public virtual DbSet<CapacityView2> CapacityView2 { get; set; }
        public virtual DbSet<CapacityProjectDuration> CapacityProjectDurations { get; set; }
        public virtual DbSet<ServiceCatalog> ServiceCatalogs { get; set; }
    }
}
