//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace NewMellat.bm.automation.jey1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LetterServiceBinding", Namespace="http://com.gam.secretariat.webservice.secure/LetterService.wsdl")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(com_gam_secretariat_webservice_complextypes_ItemWTO))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(com_gam_secretariat_webservice_complextypes_LetterPresenderWTO))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(com_gam_secretariat_webservice_complextypes_PersonDepartmentWTO))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(com_gam_secretariat_webservice_complextypes_Item))]
    public partial class LetterService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback finalRegisterLetterOperationCompleted;
        
        private System.Threading.SendOrPostCallback getReplyLettersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLetterBodyOperationCompleted;
        
        private System.Threading.SendOrPostCallback fetchLetterOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertLetterOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLetterAllAttachedFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLetterAttachmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLetterImagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback attachDocumentToLetterOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LetterService() {
            this.Url = global::NewMellat.Properties.Settings.Default.NewMellat_bm_automation_jey1_LetterService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event finalRegisterLetterCompletedEventHandler finalRegisterLetterCompleted;
        
        /// <remarks/>
        public event getReplyLettersCompletedEventHandler getReplyLettersCompleted;
        
        /// <remarks/>
        public event getLetterBodyCompletedEventHandler getLetterBodyCompleted;
        
        /// <remarks/>
        public event fetchLetterCompletedEventHandler fetchLetterCompleted;
        
        /// <remarks/>
        public event insertLetterCompletedEventHandler insertLetterCompleted;
        
        /// <remarks/>
        public event getLetterAllAttachedFilesCompletedEventHandler getLetterAllAttachedFilesCompleted;
        
        /// <remarks/>
        public event getLetterAttachmentsCompletedEventHandler getLetterAttachmentsCompleted;
        
        /// <remarks/>
        public event getLetterImagesCompletedEventHandler getLetterImagesCompleted;
        
        /// <remarks/>
        public event attachDocumentToLetterCompletedEventHandler attachDocumentToLetterCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:com-gam-secretariat-webservice-secure-LetterService/finalRegisterLetter", RequestNamespace="urn:com-gam-secretariat-webservice-secure-LetterService", ResponseNamespace="urn:com-gam-secretariat-webservice-secure-LetterService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool finalRegisterLetter(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, com_gam_secretariat_webservice_complextypes_FinalRegisterLetterParamWTO param1) {
            object[] results = this.Invoke("finalRegisterLetter", new object[] {
                        param0,
                        param1});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void finalRegisterLetterAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, com_gam_secretariat_webservice_complextypes_FinalRegisterLetterParamWTO param1) {
            this.finalRegisterLetterAsync(param0, param1, null);
        }
        
        /// <remarks/>
        public void finalRegisterLetterAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, com_gam_secretariat_webservice_complextypes_FinalRegisterLetterParamWTO param1, object userState) {
            if ((this.finalRegisterLetterOperationCompleted == null)) {
                this.finalRegisterLetterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfinalRegisterLetterOperationCompleted);
            }
            this.InvokeAsync("finalRegisterLetter", new object[] {
                        param0,
                        param1}, this.finalRegisterLetterOperationCompleted, userState);
        }
        
        private void OnfinalRegisterLetterOperationCompleted(object arg) {
            if ((this.finalRegisterLetterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.finalRegisterLetterCompleted(this, new finalRegisterLetterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:com-gam-secretariat-webservice-secure-LetterService/getReplyLetters", RequestNamespace="urn:com-gam-secretariat-webservice-secure-LetterService", ResponseNamespace="urn:com-gam-secretariat-webservice-secure-LetterService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int[] getReplyLetters(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, int param1) {
            object[] results = this.Invoke("getReplyLetters", new object[] {
                        param0,
                        param1});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void getReplyLettersAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, int param1) {
            this.getReplyLettersAsync(param0, param1, null);
        }
        
        /// <remarks/>
        public void getReplyLettersAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, int param1, object userState) {
            if ((this.getReplyLettersOperationCompleted == null)) {
                this.getReplyLettersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReplyLettersOperationCompleted);
            }
            this.InvokeAsync("getReplyLetters", new object[] {
                        param0,
                        param1}, this.getReplyLettersOperationCompleted, userState);
        }
        
        private void OngetReplyLettersOperationCompleted(object arg) {
            if ((this.getReplyLettersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReplyLettersCompleted(this, new getReplyLettersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:com-gam-secretariat-webservice-secure-LetterService/getLetterBody", RequestNamespace="urn:com-gam-secretariat-webservice-secure-LetterService", ResponseNamespace="urn:com-gam-secretariat-webservice-secure-LetterService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public com_gam_secretariat_webservice_complextypes_FileWTO getLetterBody(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, int param1) {
            object[] results = this.Invoke("getLetterBody", new object[] {
                        param0,
                        param1});
            return ((com_gam_secretariat_webservice_complextypes_FileWTO)(results[0]));
        }
        
        /// <remarks/>
        public void getLetterBodyAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, int param1) {
            this.getLetterBodyAsync(param0, param1, null);
        }
        
        /// <remarks/>
        public void getLetterBodyAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, int param1, object userState) {
            if ((this.getLetterBodyOperationCompleted == null)) {
                this.getLetterBodyOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLetterBodyOperationCompleted);
            }
            this.InvokeAsync("getLetterBody", new object[] {
                        param0,
                        param1}, this.getLetterBodyOperationCompleted, userState);
        }
        
        private void OngetLetterBodyOperationCompleted(object arg) {
            if ((this.getLetterBodyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLetterBodyCompleted(this, new getLetterBodyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:com-gam-secretariat-webservice-secure-LetterService/fetchLetter", RequestNamespace="urn:com-gam-secretariat-webservice-secure-LetterService", ResponseNamespace="urn:com-gam-secretariat-webservice-secure-LetterService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public com_gam_secretariat_webservice_complextypes_LetterWTO[] fetchLetter(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, com_gam_secretariat_webservice_complextypes_FetchLetterParamWTO param1) {
            object[] results = this.Invoke("fetchLetter", new object[] {
                        param0,
                        param1});
            return ((com_gam_secretariat_webservice_complextypes_LetterWTO[])(results[0]));
        }
        
        /// <remarks/>
        public void fetchLetterAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, com_gam_secretariat_webservice_complextypes_FetchLetterParamWTO param1) {
            this.fetchLetterAsync(param0, param1, null);
        }
        
        /// <remarks/>
        public void fetchLetterAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, com_gam_secretariat_webservice_complextypes_FetchLetterParamWTO param1, object userState) {
            if ((this.fetchLetterOperationCompleted == null)) {
                this.fetchLetterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchLetterOperationCompleted);
            }
            this.InvokeAsync("fetchLetter", new object[] {
                        param0,
                        param1}, this.fetchLetterOperationCompleted, userState);
        }
        
        private void OnfetchLetterOperationCompleted(object arg) {
            if ((this.fetchLetterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchLetterCompleted(this, new fetchLetterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:com-gam-secretariat-webservice-secure-LetterService/insertLetter", RequestNamespace="urn:com-gam-secretariat-webservice-secure-LetterService", ResponseNamespace="urn:com-gam-secretariat-webservice-secure-LetterService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int insertLetter(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, com_gam_secretariat_webservice_complextypes_LetterWTO param1) {
            object[] results = this.Invoke("insertLetter", new object[] {
                        param0,
                        param1});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void insertLetterAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, com_gam_secretariat_webservice_complextypes_LetterWTO param1) {
            this.insertLetterAsync(param0, param1, null);
        }
        
        /// <remarks/>
        public void insertLetterAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, com_gam_secretariat_webservice_complextypes_LetterWTO param1, object userState) {
            if ((this.insertLetterOperationCompleted == null)) {
                this.insertLetterOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertLetterOperationCompleted);
            }
            this.InvokeAsync("insertLetter", new object[] {
                        param0,
                        param1}, this.insertLetterOperationCompleted, userState);
        }
        
        private void OninsertLetterOperationCompleted(object arg) {
            if ((this.insertLetterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertLetterCompleted(this, new insertLetterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:com-gam-secretariat-webservice-secure-LetterService/getLetterAllAttachedFiles" +
            "", RequestNamespace="urn:com-gam-secretariat-webservice-secure-LetterService", ResponseNamespace="urn:com-gam-secretariat-webservice-secure-LetterService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public com_gam_secretariat_webservice_complextypes_FileWTO[] getLetterAllAttachedFiles(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, int param1) {
            object[] results = this.Invoke("getLetterAllAttachedFiles", new object[] {
                        param0,
                        param1});
            return ((com_gam_secretariat_webservice_complextypes_FileWTO[])(results[0]));
        }
        
        /// <remarks/>
        public void getLetterAllAttachedFilesAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, int param1) {
            this.getLetterAllAttachedFilesAsync(param0, param1, null);
        }
        
        /// <remarks/>
        public void getLetterAllAttachedFilesAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, int param1, object userState) {
            if ((this.getLetterAllAttachedFilesOperationCompleted == null)) {
                this.getLetterAllAttachedFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLetterAllAttachedFilesOperationCompleted);
            }
            this.InvokeAsync("getLetterAllAttachedFiles", new object[] {
                        param0,
                        param1}, this.getLetterAllAttachedFilesOperationCompleted, userState);
        }
        
        private void OngetLetterAllAttachedFilesOperationCompleted(object arg) {
            if ((this.getLetterAllAttachedFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLetterAllAttachedFilesCompleted(this, new getLetterAllAttachedFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:com-gam-secretariat-webservice-secure-LetterService/getLetterAttachments", RequestNamespace="urn:com-gam-secretariat-webservice-secure-LetterService", ResponseNamespace="urn:com-gam-secretariat-webservice-secure-LetterService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public com_gam_secretariat_webservice_complextypes_FileWTO[] getLetterAttachments(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, int param1) {
            object[] results = this.Invoke("getLetterAttachments", new object[] {
                        param0,
                        param1});
            return ((com_gam_secretariat_webservice_complextypes_FileWTO[])(results[0]));
        }
        
        /// <remarks/>
        public void getLetterAttachmentsAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, int param1) {
            this.getLetterAttachmentsAsync(param0, param1, null);
        }
        
        /// <remarks/>
        public void getLetterAttachmentsAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, int param1, object userState) {
            if ((this.getLetterAttachmentsOperationCompleted == null)) {
                this.getLetterAttachmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLetterAttachmentsOperationCompleted);
            }
            this.InvokeAsync("getLetterAttachments", new object[] {
                        param0,
                        param1}, this.getLetterAttachmentsOperationCompleted, userState);
        }
        
        private void OngetLetterAttachmentsOperationCompleted(object arg) {
            if ((this.getLetterAttachmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLetterAttachmentsCompleted(this, new getLetterAttachmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:com-gam-secretariat-webservice-secure-LetterService/getLetterImages", RequestNamespace="urn:com-gam-secretariat-webservice-secure-LetterService", ResponseNamespace="urn:com-gam-secretariat-webservice-secure-LetterService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public com_gam_secretariat_webservice_complextypes_FileWTO[] getLetterImages(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, int param1) {
            object[] results = this.Invoke("getLetterImages", new object[] {
                        param0,
                        param1});
            return ((com_gam_secretariat_webservice_complextypes_FileWTO[])(results[0]));
        }
        
        /// <remarks/>
        public void getLetterImagesAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, int param1) {
            this.getLetterImagesAsync(param0, param1, null);
        }
        
        /// <remarks/>
        public void getLetterImagesAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, int param1, object userState) {
            if ((this.getLetterImagesOperationCompleted == null)) {
                this.getLetterImagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLetterImagesOperationCompleted);
            }
            this.InvokeAsync("getLetterImages", new object[] {
                        param0,
                        param1}, this.getLetterImagesOperationCompleted, userState);
        }
        
        private void OngetLetterImagesOperationCompleted(object arg) {
            if ((this.getLetterImagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLetterImagesCompleted(this, new getLetterImagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:com-gam-secretariat-webservice-secure-LetterService/attachDocumentToLetter", RequestNamespace="urn:com-gam-secretariat-webservice-secure-LetterService", ResponseNamespace="urn:com-gam-secretariat-webservice-secure-LetterService")]
        public void attachDocumentToLetter(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, com_gam_secretariat_webservice_complextypes_AttachDocumentToLetterParamWTO param1) {
            this.Invoke("attachDocumentToLetter", new object[] {
                        param0,
                        param1});
        }
        
        /// <remarks/>
        public void attachDocumentToLetterAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, com_gam_secretariat_webservice_complextypes_AttachDocumentToLetterParamWTO param1) {
            this.attachDocumentToLetterAsync(param0, param1, null);
        }
        
        /// <remarks/>
        public void attachDocumentToLetterAsync(com_gam_secretariat_webservice_complextypes_SecurityContextWTO param0, com_gam_secretariat_webservice_complextypes_AttachDocumentToLetterParamWTO param1, object userState) {
            if ((this.attachDocumentToLetterOperationCompleted == null)) {
                this.attachDocumentToLetterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnattachDocumentToLetterOperationCompleted);
            }
            this.InvokeAsync("attachDocumentToLetter", new object[] {
                        param0,
                        param1}, this.attachDocumentToLetterOperationCompleted, userState);
        }
        
        private void OnattachDocumentToLetterOperationCompleted(object arg) {
            if ((this.attachDocumentToLetterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.attachDocumentToLetterCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://com.gam.secretariat.webservice.secure/LetterService.xsd")]
    public partial class com_gam_secretariat_webservice_complextypes_SecurityContextWTO {
        
        private int depIdField;
        
        private int perIdField;
        
        private string systemNameField;
        
        private string systemPassField;
        
        private string usernameField;
        
        /// <remarks/>
        public int depId {
            get {
                return this.depIdField;
            }
            set {
                this.depIdField = value;
            }
        }
        
        /// <remarks/>
        public int perId {
            get {
                return this.perIdField;
            }
            set {
                this.perIdField = value;
            }
        }
        
        /// <remarks/>
        public string systemName {
            get {
                return this.systemNameField;
            }
            set {
                this.systemNameField = value;
            }
        }
        
        /// <remarks/>
        public string systemPass {
            get {
                return this.systemPassField;
            }
            set {
                this.systemPassField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://com.gam.secretariat.webservice.secure/LetterService.xsd")]
    public partial class com_gam_secretariat_webservice_complextypes_AttachDocumentToLetterParamWTO {
        
        private int docIdField;
        
        private int docTypeIdField;
        
        private string indexFieldField;
        
        private string letterIdsField;
        
        /// <remarks/>
        public int docId {
            get {
                return this.docIdField;
            }
            set {
                this.docIdField = value;
            }
        }
        
        /// <remarks/>
        public int docTypeId {
            get {
                return this.docTypeIdField;
            }
            set {
                this.docTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string indexField {
            get {
                return this.indexFieldField;
            }
            set {
                this.indexFieldField = value;
            }
        }
        
        /// <remarks/>
        public string letterIds {
            get {
                return this.letterIdsField;
            }
            set {
                this.letterIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://com.gam.secretariat.webservice.secure/LetterService.xsd")]
    public partial class com_gam_secretariat_webservice_complextypes_ItemWTO {
        
        private int idField;
        
        private string valueField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://com.gam.secretariat.webservice.secure/LetterService.xsd")]
    public partial class com_gam_secretariat_webservice_complextypes_LetterPresenderWTO {
        
        private int depIdField;
        
        private int perIdField;
        
        private string preLetterDateField;
        
        private string preLetterNoField;
        
        private string preLetterTypeField;
        
        /// <remarks/>
        public int depId {
            get {
                return this.depIdField;
            }
            set {
                this.depIdField = value;
            }
        }
        
        /// <remarks/>
        public int perId {
            get {
                return this.perIdField;
            }
            set {
                this.perIdField = value;
            }
        }
        
        /// <remarks/>
        public string preLetterDate {
            get {
                return this.preLetterDateField;
            }
            set {
                this.preLetterDateField = value;
            }
        }
        
        /// <remarks/>
        public string preLetterNo {
            get {
                return this.preLetterNoField;
            }
            set {
                this.preLetterNoField = value;
            }
        }
        
        /// <remarks/>
        public string preLetterType {
            get {
                return this.preLetterTypeField;
            }
            set {
                this.preLetterTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://com.gam.secretariat.webservice.secure/LetterService.xsd")]
    public partial class com_gam_secretariat_webservice_complextypes_PersonDepartmentWTO {
        
        private int departmentIdField;
        
        private string departmentNameField;
        
        private string descriptionField;
        
        private int groupIdField;
        
        private int personIdField;
        
        private string personNameField;
        
        /// <remarks/>
        public int departmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
        
        /// <remarks/>
        public string departmentName {
            get {
                return this.departmentNameField;
            }
            set {
                this.departmentNameField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        public int personId {
            get {
                return this.personIdField;
            }
            set {
                this.personIdField = value;
            }
        }
        
        /// <remarks/>
        public string personName {
            get {
                return this.personNameField;
            }
            set {
                this.personNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://com.gam.secretariat.webservice.secure/LetterService.xsd")]
    public partial class com_gam_secretariat_webservice_complextypes_LetterWTO {
        
        private com_gam_secretariat_webservice_complextypes_FileWTO[] attachmentsField;
        
        private com_gam_secretariat_webservice_complextypes_FileWTO bodyField;
        
        private com_gam_secretariat_webservice_complextypes_PersonDepartmentWTO[] ccReceiversField;
        
        private int flagTypeIdField;
        
        private com_gam_secretariat_webservice_complextypes_FileWTO[] imagesField;
        
        private int[] keywordIdsField;
        
        private string letAccessTypeField;
        
        private string letAppendixField;
        
        private int letAttachmentCountField;
        
        private string letCCReceiversField;
        
        private string letCancelField;
        
        private int letCcCountField;
        
        private string letCommentField;
        
        private int letDateNumStatusField;
        
        private int letDocTypeIdField;
        
        private string letDocTypeNameField;
        
        private string letDraftDateField;
        
        private string letDraftDateModeField;
        
        private string letEffectivePreCodeField;
        
        private string letFinalRegDateField;
        
        private string letFinalRegDateModeField;
        
        private string letFinalRegFlagField;
        
        private int letFinalRegistrarPerIdField;
        
        private string letFinalRegistrarPerNameField;
        
        private string letFlowTypeField;
        
        private int letIdField;
        
        private int letImageCountField;
        
        private string letInputDateField;
        
        private string letInputDateModeField;
        
        private string letInputNoField;
        
        private string letKeywordsField;
        
        private int letNumberingIdField;
        
        private string letOrginalityField;
        
        private string letPrecodeField;
        
        private int letPresenderCountField;
        
        private int letPriorityIdField;
        
        private string letPriorityNameField;
        
        private int letProducerDepIdField;
        
        private string letProducerDepNameField;
        
        private string letProducerFullNameField;
        
        private int letProducerPerIdField;
        
        private string letProducerPerNameField;
        
        private string letProducerSendBoxStateField;
        
        private string letReceiversField;
        
        private int letRegSerialField;
        
        private int letRegYearField;
        
        private string letRegisterNumberField;
        
        private int letRegistrarDepIdField;
        
        private string letRegistrarDepNameField;
        
        private string letRegistrarFullNameField;
        
        private int letRegistrarPerIdField;
        
        private string letRegistrarPerNameField;
        
        private int letRelatedLetterCountField;
        
        private int letSenderDepIdField;
        
        private string letSenderDepNameField;
        
        private string letSenderFullNameField;
        
        private int letSenderPerIdField;
        
        private string letSenderPerNameField;
        
        private string letSenderSendBoxStateField;
        
        private string letSubjectsField;
        
        private string letSummaryField;
        
        private string letTransferField;
        
        private string letTypeField;
        
        private com_gam_secretariat_webservice_complextypes_LetterPresenderWTO[] presendersField;
        
        private com_gam_secretariat_webservice_complextypes_PersonDepartmentWTO[] receiversField;
        
        private com_gam_secretariat_webservice_complextypes_ItemWTO[] relatedLettersField;
        
        private com_gam_secretariat_webservice_complextypes_PersonDepartmentWTO[] signersField;
        
        private int[] subjectIdsField;
        
        private string summaryField;
        
        private int templateIdField;
        
        /// <remarks/>
        public com_gam_secretariat_webservice_complextypes_FileWTO[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        public com_gam_secretariat_webservice_complextypes_FileWTO body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public com_gam_secretariat_webservice_complextypes_PersonDepartmentWTO[] ccReceivers {
            get {
                return this.ccReceiversField;
            }
            set {
                this.ccReceiversField = value;
            }
        }
        
        /// <remarks/>
        public int flagTypeId {
            get {
                return this.flagTypeIdField;
            }
            set {
                this.flagTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public com_gam_secretariat_webservice_complextypes_FileWTO[] images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
            }
        }
        
        /// <remarks/>
        public int[] keywordIds {
            get {
                return this.keywordIdsField;
            }
            set {
                this.keywordIdsField = value;
            }
        }
        
        /// <remarks/>
        public string letAccessType {
            get {
                return this.letAccessTypeField;
            }
            set {
                this.letAccessTypeField = value;
            }
        }
        
        /// <remarks/>
        public string letAppendix {
            get {
                return this.letAppendixField;
            }
            set {
                this.letAppendixField = value;
            }
        }
        
        /// <remarks/>
        public int letAttachmentCount {
            get {
                return this.letAttachmentCountField;
            }
            set {
                this.letAttachmentCountField = value;
            }
        }
        
        /// <remarks/>
        public string letCCReceivers {
            get {
                return this.letCCReceiversField;
            }
            set {
                this.letCCReceiversField = value;
            }
        }
        
        /// <remarks/>
        public string letCancel {
            get {
                return this.letCancelField;
            }
            set {
                this.letCancelField = value;
            }
        }
        
        /// <remarks/>
        public int letCcCount {
            get {
                return this.letCcCountField;
            }
            set {
                this.letCcCountField = value;
            }
        }
        
        /// <remarks/>
        public string letComment {
            get {
                return this.letCommentField;
            }
            set {
                this.letCommentField = value;
            }
        }
        
        /// <remarks/>
        public int letDateNumStatus {
            get {
                return this.letDateNumStatusField;
            }
            set {
                this.letDateNumStatusField = value;
            }
        }
        
        /// <remarks/>
        public int letDocTypeId {
            get {
                return this.letDocTypeIdField;
            }
            set {
                this.letDocTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string letDocTypeName {
            get {
                return this.letDocTypeNameField;
            }
            set {
                this.letDocTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public string letDraftDate {
            get {
                return this.letDraftDateField;
            }
            set {
                this.letDraftDateField = value;
            }
        }
        
        /// <remarks/>
        public string letDraftDateMode {
            get {
                return this.letDraftDateModeField;
            }
            set {
                this.letDraftDateModeField = value;
            }
        }
        
        /// <remarks/>
        public string letEffectivePreCode {
            get {
                return this.letEffectivePreCodeField;
            }
            set {
                this.letEffectivePreCodeField = value;
            }
        }
        
        /// <remarks/>
        public string letFinalRegDate {
            get {
                return this.letFinalRegDateField;
            }
            set {
                this.letFinalRegDateField = value;
            }
        }
        
        /// <remarks/>
        public string letFinalRegDateMode {
            get {
                return this.letFinalRegDateModeField;
            }
            set {
                this.letFinalRegDateModeField = value;
            }
        }
        
        /// <remarks/>
        public string letFinalRegFlag {
            get {
                return this.letFinalRegFlagField;
            }
            set {
                this.letFinalRegFlagField = value;
            }
        }
        
        /// <remarks/>
        public int letFinalRegistrarPerId {
            get {
                return this.letFinalRegistrarPerIdField;
            }
            set {
                this.letFinalRegistrarPerIdField = value;
            }
        }
        
        /// <remarks/>
        public string letFinalRegistrarPerName {
            get {
                return this.letFinalRegistrarPerNameField;
            }
            set {
                this.letFinalRegistrarPerNameField = value;
            }
        }
        
        /// <remarks/>
        public string letFlowType {
            get {
                return this.letFlowTypeField;
            }
            set {
                this.letFlowTypeField = value;
            }
        }
        
        /// <remarks/>
        public int letId {
            get {
                return this.letIdField;
            }
            set {
                this.letIdField = value;
            }
        }
        
        /// <remarks/>
        public int letImageCount {
            get {
                return this.letImageCountField;
            }
            set {
                this.letImageCountField = value;
            }
        }
        
        /// <remarks/>
        public string letInputDate {
            get {
                return this.letInputDateField;
            }
            set {
                this.letInputDateField = value;
            }
        }
        
        /// <remarks/>
        public string letInputDateMode {
            get {
                return this.letInputDateModeField;
            }
            set {
                this.letInputDateModeField = value;
            }
        }
        
        /// <remarks/>
        public string letInputNo {
            get {
                return this.letInputNoField;
            }
            set {
                this.letInputNoField = value;
            }
        }
        
        /// <remarks/>
        public string letKeywords {
            get {
                return this.letKeywordsField;
            }
            set {
                this.letKeywordsField = value;
            }
        }
        
        /// <remarks/>
        public int letNumberingId {
            get {
                return this.letNumberingIdField;
            }
            set {
                this.letNumberingIdField = value;
            }
        }
        
        /// <remarks/>
        public string letOrginality {
            get {
                return this.letOrginalityField;
            }
            set {
                this.letOrginalityField = value;
            }
        }
        
        /// <remarks/>
        public string letPrecode {
            get {
                return this.letPrecodeField;
            }
            set {
                this.letPrecodeField = value;
            }
        }
        
        /// <remarks/>
        public int letPresenderCount {
            get {
                return this.letPresenderCountField;
            }
            set {
                this.letPresenderCountField = value;
            }
        }
        
        /// <remarks/>
        public int letPriorityId {
            get {
                return this.letPriorityIdField;
            }
            set {
                this.letPriorityIdField = value;
            }
        }
        
        /// <remarks/>
        public string letPriorityName {
            get {
                return this.letPriorityNameField;
            }
            set {
                this.letPriorityNameField = value;
            }
        }
        
        /// <remarks/>
        public int letProducerDepId {
            get {
                return this.letProducerDepIdField;
            }
            set {
                this.letProducerDepIdField = value;
            }
        }
        
        /// <remarks/>
        public string letProducerDepName {
            get {
                return this.letProducerDepNameField;
            }
            set {
                this.letProducerDepNameField = value;
            }
        }
        
        /// <remarks/>
        public string letProducerFullName {
            get {
                return this.letProducerFullNameField;
            }
            set {
                this.letProducerFullNameField = value;
            }
        }
        
        /// <remarks/>
        public int letProducerPerId {
            get {
                return this.letProducerPerIdField;
            }
            set {
                this.letProducerPerIdField = value;
            }
        }
        
        /// <remarks/>
        public string letProducerPerName {
            get {
                return this.letProducerPerNameField;
            }
            set {
                this.letProducerPerNameField = value;
            }
        }
        
        /// <remarks/>
        public string letProducerSendBoxState {
            get {
                return this.letProducerSendBoxStateField;
            }
            set {
                this.letProducerSendBoxStateField = value;
            }
        }
        
        /// <remarks/>
        public string letReceivers {
            get {
                return this.letReceiversField;
            }
            set {
                this.letReceiversField = value;
            }
        }
        
        /// <remarks/>
        public int letRegSerial {
            get {
                return this.letRegSerialField;
            }
            set {
                this.letRegSerialField = value;
            }
        }
        
        /// <remarks/>
        public int letRegYear {
            get {
                return this.letRegYearField;
            }
            set {
                this.letRegYearField = value;
            }
        }
        
        /// <remarks/>
        public string letRegisterNumber {
            get {
                return this.letRegisterNumberField;
            }
            set {
                this.letRegisterNumberField = value;
            }
        }
        
        /// <remarks/>
        public int letRegistrarDepId {
            get {
                return this.letRegistrarDepIdField;
            }
            set {
                this.letRegistrarDepIdField = value;
            }
        }
        
        /// <remarks/>
        public string letRegistrarDepName {
            get {
                return this.letRegistrarDepNameField;
            }
            set {
                this.letRegistrarDepNameField = value;
            }
        }
        
        /// <remarks/>
        public string letRegistrarFullName {
            get {
                return this.letRegistrarFullNameField;
            }
            set {
                this.letRegistrarFullNameField = value;
            }
        }
        
        /// <remarks/>
        public int letRegistrarPerId {
            get {
                return this.letRegistrarPerIdField;
            }
            set {
                this.letRegistrarPerIdField = value;
            }
        }
        
        /// <remarks/>
        public string letRegistrarPerName {
            get {
                return this.letRegistrarPerNameField;
            }
            set {
                this.letRegistrarPerNameField = value;
            }
        }
        
        /// <remarks/>
        public int letRelatedLetterCount {
            get {
                return this.letRelatedLetterCountField;
            }
            set {
                this.letRelatedLetterCountField = value;
            }
        }
        
        /// <remarks/>
        public int letSenderDepId {
            get {
                return this.letSenderDepIdField;
            }
            set {
                this.letSenderDepIdField = value;
            }
        }
        
        /// <remarks/>
        public string letSenderDepName {
            get {
                return this.letSenderDepNameField;
            }
            set {
                this.letSenderDepNameField = value;
            }
        }
        
        /// <remarks/>
        public string letSenderFullName {
            get {
                return this.letSenderFullNameField;
            }
            set {
                this.letSenderFullNameField = value;
            }
        }
        
        /// <remarks/>
        public int letSenderPerId {
            get {
                return this.letSenderPerIdField;
            }
            set {
                this.letSenderPerIdField = value;
            }
        }
        
        /// <remarks/>
        public string letSenderPerName {
            get {
                return this.letSenderPerNameField;
            }
            set {
                this.letSenderPerNameField = value;
            }
        }
        
        /// <remarks/>
        public string letSenderSendBoxState {
            get {
                return this.letSenderSendBoxStateField;
            }
            set {
                this.letSenderSendBoxStateField = value;
            }
        }
        
        /// <remarks/>
        public string letSubjects {
            get {
                return this.letSubjectsField;
            }
            set {
                this.letSubjectsField = value;
            }
        }
        
        /// <remarks/>
        public string letSummary {
            get {
                return this.letSummaryField;
            }
            set {
                this.letSummaryField = value;
            }
        }
        
        /// <remarks/>
        public string letTransfer {
            get {
                return this.letTransferField;
            }
            set {
                this.letTransferField = value;
            }
        }
        
        /// <remarks/>
        public string letType {
            get {
                return this.letTypeField;
            }
            set {
                this.letTypeField = value;
            }
        }
        
        /// <remarks/>
        public com_gam_secretariat_webservice_complextypes_LetterPresenderWTO[] presenders {
            get {
                return this.presendersField;
            }
            set {
                this.presendersField = value;
            }
        }
        
        /// <remarks/>
        public com_gam_secretariat_webservice_complextypes_PersonDepartmentWTO[] receivers {
            get {
                return this.receiversField;
            }
            set {
                this.receiversField = value;
            }
        }
        
        /// <remarks/>
        public com_gam_secretariat_webservice_complextypes_ItemWTO[] relatedLetters {
            get {
                return this.relatedLettersField;
            }
            set {
                this.relatedLettersField = value;
            }
        }
        
        /// <remarks/>
        public com_gam_secretariat_webservice_complextypes_PersonDepartmentWTO[] signers {
            get {
                return this.signersField;
            }
            set {
                this.signersField = value;
            }
        }
        
        /// <remarks/>
        public int[] subjectIds {
            get {
                return this.subjectIdsField;
            }
            set {
                this.subjectIdsField = value;
            }
        }
        
        /// <remarks/>
        public string summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
        
        /// <remarks/>
        public int templateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://com.gam.secretariat.webservice.secure/LetterService.xsd")]
    public partial class com_gam_secretariat_webservice_complextypes_FileWTO {
        
        private string commentField;
        
        private byte[] contentField;
        
        private string fileNameField;
        
        private string fileTypeField;
        
        private int idField;
        
        private int objectIdField;
        
        /// <remarks/>
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string fileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int objectId {
            get {
                return this.objectIdField;
            }
            set {
                this.objectIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://com.gam.secretariat.webservice.secure/LetterService.xsd")]
    public partial class com_gam_secretariat_webservice_complextypes_Item {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://com.gam.secretariat.webservice.secure/LetterService.xsd")]
    public partial class com_gam_secretariat_webservice_complextypes_FetchLetterParamWTO {
        
        private int fromField;
        
        private com_gam_secretariat_webservice_complextypes_Item[] itemsField;
        
        private int toField;
        
        /// <remarks/>
        public int from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public com_gam_secretariat_webservice_complextypes_Item[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public int to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://com.gam.secretariat.webservice.secure/LetterService.xsd")]
    public partial class com_gam_secretariat_webservice_complextypes_FinalRegisterLetterParamWTO {
        
        private int letterIdField;
        
        /// <remarks/>
        public int letterId {
            get {
                return this.letterIdField;
            }
            set {
                this.letterIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void finalRegisterLetterCompletedEventHandler(object sender, finalRegisterLetterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class finalRegisterLetterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal finalRegisterLetterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getReplyLettersCompletedEventHandler(object sender, getReplyLettersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReplyLettersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReplyLettersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getLetterBodyCompletedEventHandler(object sender, getLetterBodyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLetterBodyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLetterBodyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public com_gam_secretariat_webservice_complextypes_FileWTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((com_gam_secretariat_webservice_complextypes_FileWTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void fetchLetterCompletedEventHandler(object sender, fetchLetterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchLetterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fetchLetterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public com_gam_secretariat_webservice_complextypes_LetterWTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((com_gam_secretariat_webservice_complextypes_LetterWTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void insertLetterCompletedEventHandler(object sender, insertLetterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertLetterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertLetterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getLetterAllAttachedFilesCompletedEventHandler(object sender, getLetterAllAttachedFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLetterAllAttachedFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLetterAllAttachedFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public com_gam_secretariat_webservice_complextypes_FileWTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((com_gam_secretariat_webservice_complextypes_FileWTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getLetterAttachmentsCompletedEventHandler(object sender, getLetterAttachmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLetterAttachmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLetterAttachmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public com_gam_secretariat_webservice_complextypes_FileWTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((com_gam_secretariat_webservice_complextypes_FileWTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getLetterImagesCompletedEventHandler(object sender, getLetterImagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLetterImagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLetterImagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public com_gam_secretariat_webservice_complextypes_FileWTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((com_gam_secretariat_webservice_complextypes_FileWTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void attachDocumentToLetterCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591