//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMellatHR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectServer_Reporting_faEntities : DbContext
    {
        public ProjectServer_Reporting_faEntities()
            : base("name=ProjectServer_Reporting_faEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MSP_EpmResource_UserView> MSP_EpmResource_UserView { get; set; }
        public virtual DbSet<HrEmployeeDetail> HrEmployeeDetails { get; set; }
    }
}
